### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by DPr00f** [askholme/packer-builder-vultr#1]
Since this is 1 year old, the mitchellh/packer updated, which means that in order to build you need his package to be at v0.5.2, but that version requires an older version of go.crypto which I couldn't figure out which.

Could you update the package?

**Comment by askholme** [comment]
Hi

Thanks for letting me know. I'm not using this actively at the moment.

I took a quick look at it looks like a bunch of the packer plugin API changed since i wrote this, i will try to put some hours into refactoring over the next week to see if we can get this working again.

**Comment by DPr00f** [comment]
That would be awesome, I'm not that into GO Lang, but I'll give it a try as well.

**Comment by askholme** [comment]
Hi 

As you probably have figured I havn't had time to fix it. It turned out to require quite a bit of refactoring and I currently have a larger DIY project on a house i bought which takes up all my free time... So i don't expect to get this fixed in the coming months.

Sorry if you hoped to use this for something serious

**Comment by DPr00f** [comment]
No worries mate. Thanks for the explanation though.

**Comment by dradtke** [comment]
I began looking into reviving this builder, but unfortunately it seems to be built against a version of Packer old enough that it was easier to rewrite it from scratch based on a working builder: https://github.com/dradtke/packer-builder-vultr

**Comment by askholme** [comment]
Thanks for the nice word @dradtke - I'll update the description to point towards your new builder
