### ISSUE TITLE
more docs and how it works

### ISSUE THREAD

**Issue by stephencheng** [askholme/packer-builder-vultr#2]
Hi 

I am interested how this will work. It seems fun to build a gold image for vultr and spin up instantly.

Currently, I could use ansible or puppet to provision the box, but I have not attempted to use packer to do this.

My questions are:
1. what type of format vultr support for the image. I am assuming here is a snapshot, what is the format? 
2. when build the targe image, what the processes has it gone through? can you correct my guess:

a. use the vultr api to create sanpshot and download it
b. use packer to build/provision the box
c. freeze and save the box to the updated snapshot
d. upload it to vultr for future use
1. what are your go lang source code? are they for the packer plugin? or for the whole process

I'd really like some simple description to roughly explain what's happening behind the scenes

Thanks very much,

stephen

**Comment by askholme** [comment]
Hi Stephen

I think it would be worthwhile for you to read the packer (packer.io) documentation more closely.

Packer is a wrapper tools which uses a combination of plugins and provisioning tools (like ansible and puppet) to support immutable infrastructure.

In short what will happen when you use packer with this plugin is

An blank vultr box is created
A provisioning tool of choice is used to configure the box (configuration of provisioning happens through packer)
A snapshot is taken of the box and named in a specific way
The box is deleted (but the snapshot stays and can be used to create new vultr boxes)

**Comment by stephencheng** [comment]
Thanks briefing that.

As the support from vultr confirmed that they do not support either downloading or uploading snapshot, so I wonder how it is possible for this to work. Is it via uploading a customised iso image?

There are a few forum threads talking about add the feature to support download/upload snapshot, but so far it's not officially supported.

So what's the magic?

Thanks

**Comment by askholme** [comment]
The magic is that no download nor upload ever Happens. The blank Box is
provisioner via remote Access (ssh) and then stored as a snapshot.
Everything Happens on the vultr systems. Packer works as uge utility that
combines vultr api with provision tools. This is the complete standard way
of using packer.

P.s. The no upload Things is partly incorrect. Packer uses ssh for
uploading provisioning scripts to the blank Box
Br
Ask
Den 10/01/2016 11.52 skrev "Stephen Cheng" notifications@github.com:
